### ISSUE TITLE
Data service provider - Keyrock image version

### ISSUE THREAD

**Issue by pierre-josselin** [i4Trust/tutorials#2]
In the [helm chart](https://github.com/i4Trust/tutorials/blob/main/Data-Service-Provider/values/values-keyrock.yml) value file for Keyrock (in data service provider tutorial), the tag of the image to be used is **[i4trust-rc6](https://github.com/i4Trust/tutorials/blob/main/Data-Service-Provider/values/values-keyrock.yml#L15)**.

But the i4Trust support asked us to use the **i4trust-rc7** version.

Can you please confirm that we have to use **i4trust-rc7**, and if so, can you update this helm chart value ?

**Comment by dwendland** [comment]
You can use the rc7 build, this introduces an option to set the maximum header size.
Also check the updated Readme's.
The example value files have been updated.

**Comment by pierre-josselin** [comment]
Hello, I also have a question about API Umbrella version. In the [value file](https://github.com/i4Trust/tutorials/blob/main/Data-Service-Provider/values/values-umbrella.yml#L17) you use tag 0.18.0, but [i4trust tags](https://hub.docker.com/r/fiware/api-umbrella/tags?page=1&name=i4trust) also exist for this image. Should I still use 0.18.0? Thanks

**Comment by dwendland** [comment]
Please stick to 0.18.0, this is the latest version to be used for API Umbrella.
